[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  # Include prompt files and utilities in function deployment
  included_files = [
    "netlify/functions/prompts/**",
    "netlify/functions/utils/**"
  ]
  # Set Node.js runtime
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/opt/buildhome/cache/node_modules"
  VITE_EDGE_BASE = "/.netlify/functions"
  VITE_SUPABASE_URL = "https://xzngetmbbuoxjucudiyo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6bmdldG1iYnVveGp1Y3VkaXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjYzNDIsImV4cCI6MjA2MzAwMjM0Mn0.iLNY2ALVepFIRjgafeFv1dA8X5SlFACBpA3rkrkaUVo"

# Ensure all function dependencies are bundled
[functions.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200